# Validate this file using http://lint.travis-ci.org/
language: python
python:
#  - "2.5"
  - "2.6"
  - "2.7"
install:
  - "if [[ $TRAVIS_PYTHON_VERSION != '2.7' ]]; then pip install --use-mirrors argparse; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION != '2.5' ]]; then pip install --use-mirrors pysam; fi"
  - python setup.py install
script: nosetests --with-doctest
